[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:api]
command=python api.py
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/ii-researcher/api.err.log
stdout_logfile=/var/log/ii-researcher/api.out.log
priority=100
